### ISSUE TITLE
Preferred way to get standalone action-cable

### ISSUE THREAD

**Issue by pelletier** [rhyzx/actioncable#1]
Hi @rhyzx,

What is not the recommended way to use the standalone javascript for ActionCable? I would like to use it using Webpack instead of Rails' assets pipeline.

**Comment by rhyzx** [comment]
Hi @pelletier, the standalone actioncable still avaliable on [npm](https://www.npmjs.com/package/actioncable).

The reason why i stopped this project is that the Rails contributing team have taken over this package.
(sadly, however, they have not updated it yet

**Comment by pelletier** [comment]
Thanks for the explanation! The github url on the npm package page is still github.com/rhyzx/actioncable, that's why I was confused.
